include (${CMAKE_CURRENT_LIST_DIR}/Binder/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Binder/CoordinateSystemBinder/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Binder/MorisonBinder/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Binder/PileBinder/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Binder/SedimentBinder/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Binder/SedimentTransportBinder/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Binder/WaterBinder/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Binder/WaveBinder/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Binder/WaveDynamicBinder/CMakePackage.cmake)

include (${CMAKE_CURRENT_LIST_DIR}/Commands/CMakePackage.cmake)

include (${CMAKE_CURRENT_LIST_DIR}/Editor/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Editor/CoordinateSystemEditor/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Editor/MorisonEditor/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Editor/PileEditor/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Editor/SedimentEditor/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Editor/SedimentTransportEditor/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Editor/WaterEditor/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Editor/WaveDynamicEditor/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/Editor/WaveEditor/CMakePackage.cmake)

include (${CMAKE_CURRENT_LIST_DIR}/HierarchyNode/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/HierarchyNode/CoordinateSystem/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/HierarchyNode/Morison/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/HierarchyNode/Pile/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/HierarchyNode/ProjectHierarchy/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/HierarchyNode/Sediment/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/HierarchyNode/SedimentTransport/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/HierarchyNode/Water/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/HierarchyNode/Wave/CMakePackage.cmake)
    include (${CMAKE_CURRENT_LIST_DIR}/HierarchyNode/WaveDynamic/CMakePackage.cmake)

include (${CMAKE_CURRENT_LIST_DIR}/HierarchyNodeFactory/CMakePackage.cmake)
